### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by pscott-au** [jonasbn/perl-mojolicious-plugin-openapi-tutorial#1]
"Then we add the acual operation" -> "Then we add the actual operation" in README.md

**Comment by jonasbn** [comment]
Thanks @pscott-au I will patch accordingly - take care

**Comment by pscott-au** [comment]
Pod plugin I think deprecated also :)

**Comment by jonasbn** [comment]
Patched!

What POD plugin can you be more exact?

**Comment by pscott-au** [comment]
In hello world.pm prolly best to just remove

# Documentation browser under "/perldoc"
$self->plugin('PODRenderer') if $config->{perldoc};
As this causes warnings

**Comment by jonasbn** [comment]
Ah, that might be due to Mojolicious updates. I will investigate, I am unsure to whether I will update the code.
